/**
 * gen-compat-matrix.ts — M7-4 符号兼容矩阵生成脚本
 *
 * 职责：
 * 1. 扫描 packages/bun-types/**\/*.d.ts，提取所有公开符号
 * 2. 对比 CompatRegistry 中的登记情况，输出未登记符号列表
 * 3. 产出 COMPAT.md（Markdown 兼容矩阵表格）
 * 4. 若有未登记符号且 --fail 模式，则 exit(1)（供 CI 门禁使用）
 *
 * 使用方式：
 *   bun scripts/gen-compat-matrix.ts [--fail] [--output=COMPAT.md]
 *
 * CI 集成：在 .github/workflows/web-runtime.yml 中调用此脚本，
 * 未登记符号时 CI 失败（--fail 参数）。
 */

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { parseArgs } from 'node:util'
import { scanDtsContent } from '../packages/bun-web-compat-registry/src/scanner'
import type { CompatEntry } from '../packages/bun-web-compat-registry/src/compat.types'

// ── CLI 参数 ──────────────────────────────────────────────────────────────────

const { values } = parseArgs({
  options: {
    fail: { type: 'boolean', default: false },
    output: { type: 'string', default: 'COMPAT.md' },
    'types-dir': { type: 'string', default: 'packages/bun-types' },
    'registry-path': { type: 'string', default: 'packages/bun-web-compat-registry/src/entries.ts' },
  },
})

const shouldFail = values.fail ?? false
const outputPath = values.output ?? 'COMPAT.md'
const typesDir = resolve(values['types-dir'] ?? 'packages/bun-types')
const registryEntryPath = resolve(values['registry-path'] ?? 'packages/bun-web-compat-registry/src/entries.ts')

// ── 扫描 bun-types ────────────────────────────────────────────────────────────

function collectDtsFiles(dir: string): string[] {
  const files: string[] = []
  if (!existsSync(dir)) return files
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...collectDtsFiles(full))
    } else if (entry.isFile() && entry.name.endsWith('.d.ts')) {
      files.push(full)
    }
  }
  return files
}

const dtsFiles = collectDtsFiles(typesDir)
const allSymbols = new Set<string>()

for (const file of dtsFiles) {
  const content = readFileSync(file, 'utf8')
  for (const sym of scanDtsContent(content, file)) {
    allSymbols.add(sym)
  }
}

// ── 读取 entries（若存在）─────────────────────────────────────────────────────

let registeredEntries: CompatEntry[] = []

if (existsSync(registryEntryPath)) {
  // 动态 import：entries.ts 必须 export default CompatEntry[]
  const mod = await import(registryEntryPath)
  const raw = mod.default ?? mod.entries ?? []
  if (Array.isArray(raw)) {
    registeredEntries = raw
  }
}

const registeredSymbols = new Map<string, CompatEntry>(
  registeredEntries.map(e => [e.symbol, e]),
)

// ── 对比分析 ──────────────────────────────────────────────────────────────────

const missing: string[] = []
for (const sym of allSymbols) {
  if (!registeredSymbols.has(sym)) {
    missing.push(sym)
  }
}
missing.sort()

// ── 产出 COMPAT.md ─────────────────────────────────────────────────────────────

function levelBadge(level: string): string {
  const map: Record<string, string> = {
    A: '🟢 A',
    B: '🟡 B',
    C: '🟠 C',
    D: '🔴 D',
  }
  return map[level] ?? level
}

const lines: string[] = [
  '# Compat Matrix',
  '',
  `> Generated by \`scripts/gen-compat-matrix.ts\` — do not edit manually.`,
  `> Total symbols: **${allSymbols.size}** | Registered: **${registeredSymbols.size}** | Missing: **${missing.length}**`,
  '',
  '## Registered Symbols',
  '',
  '| Symbol | Level | Since | Notes |',
  '|--------|-------|-------|-------|',
]

for (const entry of [...registeredEntries].sort((a, b) => a.symbol.localeCompare(b.symbol))) {
  const since = entry.since ?? '—'
  const notes = entry.notes ? entry.notes.replace(/\|/g, '\\|') : '—'
  lines.push(`| \`${entry.symbol}\` | ${levelBadge(entry.level)} | ${since} | ${notes} |`)
}

if (missing.length > 0) {
  lines.push(
    '',
    '## ⚠️ Unregistered Symbols (need compat entry)',
    '',
    '| Symbol |',
    '|--------|',
    ...missing.map(s => `| \`${s}\` |`),
  )
}

writeFileSync(outputPath, lines.join('\n') + '\n', 'utf8')
console.log(`[gen-compat-matrix] Written: ${outputPath}`)
console.log(`  Scanned ${dtsFiles.length} .d.ts files → ${allSymbols.size} symbols`)
console.log(`  Registered: ${registeredSymbols.size} | Missing: ${missing.length}`)

// ── CI 门禁 ──────────────────────────────────────────────────────────────────

if (missing.length > 0 && shouldFail) {
  console.error(`\n[gen-compat-matrix] FAIL: ${missing.length} symbols not registered in CompatRegistry:`)
  for (const sym of missing.slice(0, 20)) {
    console.error(`  - ${sym}`)
  }
  if (missing.length > 20) {
    console.error(`  ... and ${missing.length - 20} more`)
  }
  process.exit(1)
}
