var EE=require('events');
function _inherits(C,P){C.prototype=Object.create(P.prototype);C.prototype.constructor=C;}
function IncomingMessage(url,method,headers){EE.call(this);this.url=url||'/';this.method=method||'GET';this.headers=headers||{};this.statusCode=200;this.statusMessage='OK';}
_inherits(IncomingMessage,EE);
function ServerResponse(){EE.call(this);this.statusCode=200;this.statusMessage='OK';this.headers={};}
_inherits(ServerResponse,EE);
ServerResponse.prototype.setHeader=function(k,v){this.headers[k.toLowerCase()]=v;return this;};
ServerResponse.prototype.getHeader=function(k){return this.headers[k.toLowerCase()];};
ServerResponse.prototype.removeHeader=function(k){delete this.headers[k.toLowerCase()];};
ServerResponse.prototype.writeHead=function(code,msg,h){this.statusCode=code;if(typeof msg==='object')Object.assign(this.headers,msg);else if(h)Object.assign(this.headers,h);return this;};
ServerResponse.prototype.write=function(d,e,cb){if(typeof e==='function'){cb=e;}if(cb)setTimeout(cb,0);return true;};
ServerResponse.prototype.end=function(d,e,cb){if(typeof d==='function'){cb=d;d=null;}else if(typeof e==='function'){cb=e;e=null;}if(d!=null)this.write(d,e);if(cb)setTimeout(cb,0);this.emit('finish');return this;};
function _mkReq(opts,cb){if(typeof opts==='string')opts={href:opts};var url=opts.href||opts.url||((opts.protocol||'http:')+'//'+(opts.host||opts.hostname||'localhost')+(opts.port?':'+opts.port:'')+(opts.path||'/'));var method=(opts.method||'GET').toUpperCase(),chunks=[],hdrs=opts.headers||{};var req=Object.create(EE.prototype);EE.call(req);req.write=function(d){chunks.push(typeof d==='string'?d:new TextDecoder().decode(d instanceof Uint8Array?d:new Uint8Array(d.buffer||d)));return true;};req.end=function(d,e,cb2){if(typeof d==='function'){cb2=d;d=null;}if(d)req.write(d);var body=chunks.length&&method!=='GET'&&method!=='HEAD'?chunks.join(''):undefined;fetch(url,{method:method,headers:hdrs,body:body}).then(function(r){var res=new IncomingMessage(url,method,{});r.headers.forEach(function(v,k){res.headers[k]=v;});res.statusCode=r.status;res.statusMessage=r.statusText||'';if(cb)cb(res);return r.arrayBuffer();}).then(function(ab){}).catch(function(e){req.emit('error',e);});if(cb2)setTimeout(cb2,0);return req;};req.setHeader=function(k,v){hdrs[k.toLowerCase()]=v;return req;};req.getHeader=function(k){return hdrs[k.toLowerCase()];};req.setTimeout=function(){return req;};req.destroy=function(){return req;};req.abort=function(){};return req;}
function createServer(h){var srv={listen:function(port,host,cb){if(typeof host==='function'){cb=host;}if(typeof cb==='function')setTimeout(cb,0);return srv;},close:function(cb){if(cb)setTimeout(cb,0);return srv;},on:function(){return srv;},once:function(){return srv;},emit:function(){return srv;},address:function(){return{port:0,family:'IPv4',address:'127.0.0.1'};}};return srv;}
var STATUS_CODES={100:'Continue',200:'OK',201:'Created',202:'Accepted',204:'No Content',206:'Partial Content',301:'Moved Permanently',302:'Found',304:'Not Modified',400:'Bad Request',401:'Unauthorized',403:'Forbidden',404:'Not Found',405:'Method Not Allowed',408:'Request Timeout',409:'Conflict',422:'Unprocessable Entity',429:'Too Many Requests',500:'Internal Server Error',501:'Not Implemented',502:'Bad Gateway',503:'Service Unavailable',504:'Gateway Timeout'};
module.exports={request:_mkReq,get:function(o,cb){var r=_mkReq(o,cb);r.end();return r;},createServer:createServer,STATUS_CODES:STATUS_CODES,IncomingMessage:IncomingMessage,ServerResponse:ServerResponse,METHODS:['GET','POST','PUT','DELETE','PATCH','HEAD','OPTIONS','TRACE','CONNECT'],globalAgent:{maxSockets:Infinity}};
